# Generated by Django 5.1 on 2024-08-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="code",
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
