# Generated by Django 5.1 on 2024-08-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_alter_permission_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="roles",
            field=models.ManyToManyField(related_name="persons", to="ecommerce.role"),
        ),
    ]
