# Generated by Django 5.1 on 2024-08-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0004_alter_role_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                null=True, related_name="roles", to="ecommerce.permission"
            ),
        ),
    ]
