# Generated by Django 5.1 on 2024-08-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0005_alter_role_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                related_name="roles", to="ecommerce.permission"
            ),
        ),
    ]
